import json
from pypdf import PdfReader
# Reviewed against official upgrade cards v1.6 (page numbers are 1-based).
rows=[
('YARI','Kassen Buki: Yari-tsukai',1,'EMPIRE_OF_SOGA',2,0),('NAGAMAKI','Kassen Buki: Nagamaki-tsukai',2,'EMPIRE_OF_SOGA',2,0),('DAIKYUU','Kassen Buki: Daikyuu-tsukai',3,'EMPIRE_OF_SOGA',3,0),('KANABOU','Kassen Buki: Kanabou-tsukai',4,'EMPIRE_OF_SOGA',3,0),('BUJUTSU','Bujutsu Expertise',5,'EMPIRE_OF_SOGA',3,2),('KYUJUTSU','Kyujutsu Expertise',6,'EMPIRE_OF_SOGA',3,2),('LUCKY_CHARM','Lucky Charm',7,'EMPIRE_OF_SOGA',3,1),('DUELIST','Traveling Duelist',8,'EMPIRE_OF_SOGA',3,2),('SEASONED','Seasoned Combatant',9,'EMPIRE_OF_SOGA,HELIAN_LEAGUE',2,0),
('POISON','Poisoned Weapons',11,'COALITION_OF_THENION',2,0),('MUFFLED','Muffled Movement',12,'COALITION_OF_THENION',2,0),('CLIMBING','Climbing Expertise',13,'COALITION_OF_THENION',2,0),('FANGS','Fangs of Tiamat',15,'COALITION_OF_THENION',2,0),('CONCEALED','Concealed Approach',17,'COALITION_OF_THENION',3,0),('TIAMAT','Devotion: Tiamat',18,'COALITION_OF_THENION',1,0),('ANRAS','Devotion: Anras',19,'COALITION_OF_THENION',1,0),('PAIMON','Devotion: Paimon',20,'COALITION_OF_THENION',2,0),
('TOME','Arcane Tome',21,'SAND_KINGDOMS',4,0),('GUARD','Personal Guard',23,'SAND_KINGDOMS',3,0),('AMPLIFIER','Casting Amplifier',24,'SAND_KINGDOMS',2,0),('LINEAGE','Elemental Lineage',26,'SAND_KINGDOMS',4,2),('CARPET','Flying Carpet',27,'SAND_KINGDOMS',4,1),('RETINUE','Conjured Retinue',28,'SAND_KINGDOMS',3,1),('CATALYST','Mana Catalyst',29,'SAND_KINGDOMS',1,0),
('TACTICAL','Tactical Expertise',31,'HELIAN_LEAGUE',3,1),('HAIRON','Companion of Hairon',32,'HELIAN_LEAGUE',2,2),('SHAPER','Adept Shaper',34,'HELIAN_LEAGUE',3,2),('WEIGHT','Glyphscribe: Reduce Weight',36,'HELIAN_LEAGUE',3,0),('PROVIDENCE','Glyphscribe: Hyperia’s Providence',37,'HELIAN_LEAGUE',3,0),('DOUBLE_TIME','Expeditionary Tactics: Double Time',38,'HELIAN_LEAGUE',3,1),('SURGE','Expeditionary Tactics: Surge Order',39,'HELIAN_LEAGUE',3,1),('LONGEVITY','Gift of Longevity',40,'HELIAN_LEAGUE',1,2),
('POUCH','Pouch',41,'NEUTRAL',1,0),('FIRST_AID','First Aid',43,'NEUTRAL',2,2),('CAMARADERIE','Camaraderie',45,'NEUTRAL',5,3),('PROTECTION','Additional Protection',46,'NEUTRAL',2,0),('IMPORTED_AMPLIFIER','Imported Casting Amplifier',47,'NEUTRAL',4,1),('CROSSBOW','Imported Crossbow',48,'NEUTRAL',5,1),('UTILITY','Utility Tool',49,'NEUTRAL',1,0),('SMOKESCREEN','Smokescreen',50,'NEUTRAL',2,2),('SPEAR','King of the Battlefield',51,'NEUTRAL',2,0),('EXPEDITION','Expedition Leader',52,'NEUTRAL',5,0),('RAID','Raid Leader',53,'NEUTRAL',4,0),('JOURNEYMAN','Journeyman Adventurer',54,'NEUTRAL',3,0)]
reader=PdfReader('data/sources/upgrades.pdf')
data={'version':'upgrades-1.6-reviewed-2026-08-31','source':'https://drive.google.com/file/d/17pWzpYt1GLh2Hb4DgQXupa4XL09J_xad/view','records':[{'id':id,'name':name,'page':page,'factions':factions.split(','),'cost':cost,'limit':limit or None,'description':reader.pages[page-1].extract_text()} for id,name,page,factions,cost,limit in rows]}
with open('data/upgrades.json','w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
